framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://'
            failed: 'doctrine://default?queue_name=failed'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            changelog:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                 queues:
                    changelog: ~
                serializer: App\Messenger\Serializer\ChangelogSerializer

        routing:
            App\Message\Changelog: changelog

when@test:
   framework:
       messenger:
           transports:
               async: 'in-memory://'
